_BASE_: "../../../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "output/defrcn/r101_faster/coco_trained/base/r101_faster_rcnn_c4/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: false
    FREEZE_AT: 3
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: -1 # please setup here within overwritting cfg
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01 
    FREEZE_FEAT: True 
    CLS_DROPOUT: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7 # detectron2 default is 14. Because the c4 config never load Base-RCNN-FPN.yaml, we need to set this manually here.
    # Otherwise, ther POOLER_RESOLUTION will be 14, which is inconsistent from the pre-trained base model (res=7). 
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0 # following GLIP, set weight decay as 0.0 for bias parameters
  OPTIMIZER: "ADAMW"
  STEPS: (999998, 999999)
  MAX_ITER: 1000000 # maximum iteration: useful for large-size dataset to apply short-training
  BASE_LR: 0.01
  OPTIMIZER: "SGD"
  # === custom ===
  CHECKPOINT_PERIOD: 1000000 # save only final checkpoint
  MAX_EPOCH: 200
  WARMUP_ITERS: 0
  EPOCH_ITER: 'epoch'
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
  USE_AUTOSTEP: True
  STEP_PATIENCE: 3
  # === 
INPUT:
  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (480, 560, 640, 720, 800) # GLIP style
VERSION: 2
SEED: 42 # set random seed
TEST:
  EVAL_PERIOD: 10000
  EVAL_EPOCH: 1 # eval every n epochs
  PCB_ENABLE: True
  USE_ORG_PCB: True
  PCB_MODELTYPE: resnet
  PCB_MODELPATH: ~/.torch/models/resnet101-5d3b4d8f.pth
FEWSHOT:
  FREEZE_METHOD: 'defrcn'