_BASE_: "dyhead_swint_atss_fpn_2x_ms_IN1K_mix_coco_o365_100.yaml"
DATASETS:
  TRAIN: ("mix_coco_o365_train_001",) # 0.002M = 2K
  TEST: ("object365_06m_val",)
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.05 # [fix error whten optimize]
  # IMS_PER_BATCH: 64 # it seems to work when 1gpu=8batch for A6000
  # STEPS: (620, 830)
  # MAX_ITER: 940 # mix_01=2K | 2K / 64 = 31.2 iters | 31.2 * 30 epochs = 936 iters
  # [same iters as 100%]
  IMS_PER_BATCH: 64 # it seems to work when 1gpu=8batch for A6000
  STEPS: (61900, 82500)
  MAX_ITER: 93750 # mix_100=0.2M | 0.2M / 64 = 3125 iters | 3125 * 30 epochs = 93750 iters
  OPTIMIZER: "ADAMW"
INPUT:
  FORMAT: "RGB"
  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (480, 560, 640, 720, 800) # GLIP style
VERSION: 2