_BASE_: "dyhead_swint_atss_fpn_2x_ms_IN1K_mix_coco_o365_100.yaml"
DATASETS:
  TRAIN: ("mix_coco_o365_train_030",) # 0.06M
  TEST: ("object365_06m_val",)
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.05 # [fix error whten optimize]
  # IMS_PER_BATCH: 64 # it seems to work when 1gpu=8batch for A6000
  # STEPS: (18600, 24800)
  # MAX_ITER: 28200 # mix_30=60K=0.06M | 60K / 64 = 940 iters | 940 * 30 epochs = 28125 iters
  # [same iters as 100%]
  IMS_PER_BATCH: 64 # it seems to work when 1gpu=8batch for A6000
  STEPS: (61900, 82500)
  MAX_ITER: 93750 # mix_100=0.2M | 0.2M / 64 = 3125 iters | 3125 * 30 epochs = 93750 iters
  OPTIMIZER: "ADAMW"
INPUT:
  FORMAT: "RGB"
  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (480, 560, 640, 720, 800) # GLIP style
VERSION: 2