_BASE_: "../fewshot/odinw/_faster_base_fullft.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NUM_CLASSES: -1
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  # [2500 iters]
  # STEPS: (2000, )
  # MAX_ITER: 2500
  # CHECKPOINT_PERIOD: 2500
  # [1000 iters]
  STEPS: (600,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000
  # === follow not the dynamic termination such as STEP_PATIENCE, but fixed train iters ===
  EPOCH_ITER: 'iter'
  USE_AUTOSTEP: False # turn off 'plateau' scheduler', and use WarmupMultiStepLR
  STEP_PATIENCE: -1
  AUTO_TERMINATE_PATIENCE: -1
KD:
  # BURN_UP_STEP: 1500
  BURN_UP_STEP: 500
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.999
  LOSS_WEIGHT: 4.0
  DISABLE_TEACHER_EVAL: True # eval only for student
TEST:
  EVAL_PERIOD: 100
FEWSHOT:
  FREEZE_METHOD: distill_cdfsod

# 1000 iters
# SOLVER.STEPS: (600, )
# SOLVER.MAX_ITER: 1000
# KD.BURN_UP_STEP: 500

# 2500 iters
# SOLVER.STEPS: (2000, )
# SOLVER.MAX_ITER: 2500
# KD.BURN_UP_STEP: 1500