_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 3 # even base training, freeze at 3
    FREEZE: false ### 
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 80 # no need to add background class
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7 # detectron2 default is 14. Because the c4 config never load Base-RCNN-FPN.yaml, we need to set this manually here.
    # Otherwise, ther POOLER_RESOLUTION will be 14, which is inconsistent from the pre-trained base model (res=7). 
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 5e-5
  WEIGHT_DECAY_BIAS: 5e-5
  EPOCH_ITER: 'iter'
  CHECKPOINT_PERIOD: 10000
INPUT:
  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (480, 560, 640, 720, 800) # GLIP style
# TEST:
#   EVAL_PERIOD: 10000
#   EVAL_EPOCH: 1 # eval every n epochs
#   PCB_ENABLE: True
#   USE_ORG_PCB: True
#   PCB_MODELTYPE: resnet
#   PCB_MODELPATH: ~/.torch/models/resnet101-5d3b4d8f.pth
# FEWSHOT:
#   FREEZE_METHOD: 'defrcn'